global:
  resolve_timeout: 5m

route:
  receiver: 'local-script'
  group_wait: 10s        # Wait 10 seconds before sending the first notification
  group_interval: 30s    # Wait at least 30 seconds between notifications for a group
  repeat_interval: 5m    # Resend the alert every 5 minutes if still firing

receivers:
  - name: 'local-script'
    webhook_configs:
      - url: 'http://localhost:5001/' # URL for the local webhook server
