groups:
  - name: demo_alerts
    rules:
      # Alert for high CPU usage
      - alert: HighCPUUsage
        expr: sum(rate(node_cpu_seconds_total{mode="user"}[30s])) / count(node_cpu_seconds_total{mode="user"}) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 1 minute."

      # Alert for low available memory
      - alert: LowAvailableMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.2
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low memory available"
          description: "Available memory is below 20%."

      # Alert for container high memory usage
      - alert: ContainerHighMemory
        expr: sum(rate(container_memory_usage_bytes[1m])) by (container_name) > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.container_name }} is using high memory"
          description: "Memory usage exceeds 500MB for container {{ $labels.container_name }}."
